name: Build and deploy Next.js app to Azure Web App - service-la-web

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app (Standalone)
        run: npm run build

      - name: Upload standalone build for deployment
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-standalone
          path: .next/standalone

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write # Required for OIDC login
      contents: read # Required for actions/checkout

    steps:
      - name: Download standalone build artifact
        uses: actions/download-artifact@v4
        with:
          name: nextjs-standalone
          path: .next/standalone

      - name: Azure Login via OIDC
        uses: azure/login@v1
        with:
          auth-type: oidc
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3B1A5569A67A4E8EB11F6E2DEE104EB7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_125731433A6840FBA1A80F85745BE73F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4FA921E21E594D90951CFAE2F0B3EE77 }}

      - name: Install production dependencies in standalone
        run: |
          cd .next/standalone
          npm ci --production

      - name: Deploy Next.js Standalone Build to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'service-la-web'
          slot-name: 'Production'
          package: .next/standalone