name: Build and deploy Next.js app to Azure Web App - service-la-web

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app (Standalone)
        run: npm run build

      - name: Upload standalone build for deployment
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-standalone
          path: .next/standalone

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - name: Download standalone build artifact
        uses: actions/download-artifact@v4
        with:
          name: nextjs-standalone
          path: standalone

      - name: Azure Login via Service Principal
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8FDFCE1149AA4B39AB471B9CC6E7E9D7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_466E8579BF234BC0B2D9ED7060F8B26A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DC3856FA79374AE282B52C4690740A0C }}


      - name: Deploy Next.js Standalone Build to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'service-la-web'
          slot-name: 'Production'
          package: standalone
