name: Build and Deploy to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js if needed (adjust version for your project)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      # Install dependencies & build
      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      # Azure login using OIDC
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DA3CE588AF334CA3813CFC77867C073F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E7D84F3DACAF46C8B667A19161E8BCE2 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7CA0FBDF53704D6BA7EC0D2F508E637C }}
          
      # Deploy to Azure Web App
      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: my-next-app           # Replace with your Azure Web App name
          package: .                      # Path to your build output folder

      - name: Azure Logout
        run: az logout
